# Backend CI/CD - Cloud Build configuration
# Triggered on push to main branch when backend/ files change

steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/centro-carreiras-api:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/centro-carreiras-api:latest'
      - '.'
    dir: 'backend'
    id: 'build'

  # Push the image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/centro-carreiras-api:$COMMIT_SHA'
    id: 'push'
    waitFor: ['build']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'centro-carreiras-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/centro-carreiras-api:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'FRONTEND_URL=${_FRONTEND_URL}'
      - '--set-env-vars'
      - 'FIREBASE_PROJECT_ID=${_FIREBASE_PROJECT_ID}'
      - '--set-env-vars'
      - 'AIRTABLE_API_TOKEN=${_AIRTABLE_API_TOKEN}'
      - '--set-env-vars'
      - 'AIRTABLE_BASE_ID=${_AIRTABLE_BASE_ID}'
      - '--set-env-vars'
      - 'AIRTABLE_MENTORS_TABLE=${_AIRTABLE_MENTORS_TABLE}'
      - '--set-env-vars'
      - 'MIXPANEL_TOKEN=${_MIXPANEL_TOKEN}'
      - '--set-env-vars'
      - 'RESEND_API_KEY=${_RESEND_API_KEY}'
      - '--set-env-vars'
      - 'EMAIL_FROM_ADDRESS=${_EMAIL_FROM_ADDRESS}'
      - '--set-env-vars'
      - 'EMAIL_ADMIN_CC=${_EMAIL_ADMIN_CC}'
    id: 'deploy'
    waitFor: ['push']

# Substitution variables (set in Cloud Build Trigger)
substitutions:
  _REGION: 'southamerica-east1'
  _FRONTEND_URL: 'https://centro-carreiras-web-129179710207.us-east1.run.app'
  _FIREBASE_PROJECT_ID: 'centro-carreiras-fire'
  _AIRTABLE_API_TOKEN: ''
  _AIRTABLE_BASE_ID: ''
  _AIRTABLE_MENTORS_TABLE: 'mentores_residentes_prod'
  _MIXPANEL_TOKEN: ''
  _RESEND_API_KEY: ''
  _EMAIL_FROM_ADDRESS: 'Centro de Carreiras <noreply@patronos.org>'
  _EMAIL_ADMIN_CC: 'contato@patronos.org'

images:
  - 'gcr.io/$PROJECT_ID/centro-carreiras-api:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/centro-carreiras-api:latest'

options:
  logging: CLOUD_LOGGING_ONLY
